### ISSUE TITLE
Peer-Feedback (Alex)

### ISSUE THREAD

**Issue by ehhope** [UBC-MDS/DSCI_532_Arzan_Brenden#12]
Some points:

- A little bit of text would go a long way in providing context to the graphs, even though it's clear what they represent it would be nice to have a few words
- Some kind of graph either on 1 of the line graphs you have or perhaps an additional bar graph in bottom left that represents aggregate scores of all the cities where you use the line graphs for more precise time comparisons and bar graph for aggregate measures.
- Dropdown menu to compare more cities
- Have a question people can choose at the top that directs them into the graphs on how to use them, so they pick a crime and then tweak the year to explore their 'question' on the graph. Helps orient the viewer.

**Comment by everittB** [comment]
Completed. c018231d56a48492bb86d8d747b1df36d3257de6
