### ISSUE TITLE
Milestone 3 - Review by Sabrina (sabrinatkk)

### ISSUE THREAD

**Issue by sabrinatkk** [UBC-MDS/DSCI_532_Arzan_Brenden#13]
Good:
- Tabs are great to have to separate different crime types to avoid "information overload" on one page.
-  the graphs are working perfectly, and interactive with the year range.

Improvement:
- Font size for labelling should be bigger.
-  The variable name on y-axis should remove the underscore. 
- As a user, I would like to see a homepage to compare cities on crime rate for each crime type. (bar graphs)

**Comment by everittB** [comment]
Completed. c018231d56a48492bb86d8d747b1df36d3257de6
