### ISSUE TITLE
App Improvements

### ISSUE THREAD

**Issue by everittB** [UBC-MDS/DSCI_532_Arzan_Brenden#5]
1. Make style changes to plots 
 1. Axis's
 2. Backgrounds
 3. Fonts  
 4. Colors
 5. Fine tune plots reactivity

**Comment by nazra-inari** [comment]
I think you've pretty much taken care of all of these, right? I'm gonna work on trying to deploy the app

**Comment by everittB** [comment]
Commit Sha: dc0e1e9f158c3c0da5f6d715d2599ef17ca6233c
